### ISSUE TITLE
[BUG] SQL error in scheduler when queue is empty

### ISSUE THREAD

**Issue by tm-lmathieu** [toumoro/ext-solr#1]
**Describe the bug**
SQL error in scheduler when queue is empty

**To Reproduce**
1. Once everything is indexed (or empty the queue, I guess)
2. Go to 'scheduler'
3. Look at the error

```
<span class="label label-danger" title="L'exécution a échoué : 0, An exception occurred while executing 'UPDATE `tx_solr_indexqueue_item` SET `lockeduntil` = ? WHERE `uid` IN ()' with params [1638609359]:
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1">échec</span>
```

**Expected behavior**
It should not give an error.

**Comment by simouel** [comment]
Dear @tm-lmathieu,
May you test the latest commit to see if everything works for you now.

Sincerely.

**Comment by tm-lmathieu** [comment]
The error doesn't appear anymore. Thank you, Mr, Simouel.
